import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { AuthService } from '../../core/auth.service';
@Component({imports: [FormsModule, RouterLink, MatButtonModule, MatFormFieldModule, MatInputModule], template: `<main class="auth-page"><section class="auth-card"><h1>BuildTrack</h1><h2>Sign up</h2><form (ngSubmit)="submit()"><mat-form-field class="form-field"><mat-label>Full name</mat-label><input matInput name="name" [(ngModel)]="full_name" required></mat-form-field><mat-form-field class="form-field"><mat-label>Email</mat-label><input matInput type="email" name="email" [(ngModel)]="email" required></mat-form-field><mat-form-field class="form-field"><mat-label>Password</mat-label><input matInput type="password" name="password" [(ngModel)]="password" required minlength="8"><mat-hint>Use uppercase, lowercase and a number.</mat-hint></mat-form-field>@if (message) {<p class="success">{{message}}</p>} @if (error) {<p class="error">{{error}}</p>}<button mat-flat-button color="primary" type="submit" [disabled]="loading">{{loading ? 'Creating…' : 'Create account'}}</button></form><p>Already registered? <a routerLink="/login">Sign in</a></p></section></main>`})
export class SignupComponent { full_name=''; email=''; password=''; error=''; message=''; loading=false; constructor(private auth: AuthService) {} submit() { this.error=''; this.message=''; this.loading=true; this.auth.signup({full_name:this.full_name,email:this.email,password:this.password}).subscribe({next:()=>{this.message='Account created. You can now sign in.';this.loading=false;},error:e=>{this.error=e.error?.detail || 'Unable to create account.';this.loading=false;}}); } }
